### ISSUE TITLE
Brass plate recipe not working in all patterns

### ISSUE THREAD

**Issue by TheDutchMC04** [Iskallia/FunCraft#16]
![image](https://user-images.githubusercontent.com/28569170/69559525-69aca300-0faa-11ea-93a6-fbc87af9e775.png)

![image](https://user-images.githubusercontent.com/28569170/69559549-74673800-0faa-11ea-848f-dac195a0cc10.png)

the pictures explain.

Brass plates and ingots from Railcraft

**Comment by Enderized** [comment]
Not an issue but actually intended- its a shaped recipe- always has been and will ever be.
would be an enhancement tho

**Comment by TheDutchMC04** [comment]
it might be a shaped recipe, but should not really be
