### ISSUE TITLE
FC Private - Bits crafting

### ISSUE THREAD

**Issue by Hellhium** [Iskallia/FunCraft#18]
Crafting bits is buggy because of the collision with the emerald nugget craft
Can we add a new recipe with 5 emeralds crafted into 500 bits ?

**Comment by Enderized** [comment]
You have this small little arrow when you craft emeralds into either Nuggets or Bits, letting you decide which to use. => https://i.imgur.com/wdhFNSN.png

tho it doesnt work for AE2 Autocrafting sadly-

As Emerald Nuggets are completely unused, i would suggest just removing the Emerald Nugget Recipe.
Also the idea of directly 5 emeralds into 500 bits is also nice for bulk-crafting

**Comment by Hellhium** [comment]
I'm sorry, should have linked that video before, this is what happens when I shift right click the craft
https://www.youtube.com/watch?v=bEuhFQpiIb4&feature=youtu.be

**Comment by aolsen96** [comment]
i wil add a recipe for 500 bits. gonna leav it up til its done tho

**Comment by NightmareDoctor** [comment]
itraders.zs
->

recipes.addShapeless(<itraders:bit_500>, [<minecraft:emerald>,<minecraft:emerald>,<minecraft:emerald>,<minecraft:emerald>,<minecraft:emerald>]);
