### ISSUE TITLE
Mekanism induction cell capacity wrong

### ISSUE THREAD

**Issue by TheDutchMC04** [Iskallia/FunCraft#2]
The capacity's for Mekanism Induction Cell (tier elite and ultimate) are the wrong. Ultimate and Elite are the same as the advanced. Induction cell is part of a multiblock

**Comment by aolsen96** [comment]
that is a bug with the version off mekanism that is currently in use and has been fix in the next verion

**Comment by TheDutchMC04** [comment]
Version 1.1, issue is still present :)
