### ISSUE TITLE
update 1.1.1 not working

### ISSUE THREAD

**Issue by reinaerd** [Iskallia/FunCraft#25]
when i try to update, I cant

![Aantekening 2019-12-03 191237](https://user-images.githubusercontent.com/58473900/70077341-e79f2880-1600-11ea-9256-a011a3d49838.png)

**Comment by reinaerd** [comment]
it only works if i create a new profile, but then i would lose an awfull lot of effort from my previous save

**Comment by Enderized** [comment]
That's a Twitch Client Issue-
nothing we can do about it afaik...

Update to a new profile, then copy your world files over from 
`Twitch\Minecraft\Instances\FunCraft - FC\saves`
to `Twitch\Minecraft\Instances\FunCraft - FC (1)\saves`

**Comment by reinaerd** [comment]
why does it suddenly use 93% of my memory and keeps freezing? Is there any way to fix this? @Enderized

**Comment by Enderized** [comment]
You have to allocate more ram to the new Twitch Profile

Rightclick new Profile -> Profile Options -> Uncheck 2nd Checkbox and set RAM :)

**Comment by reinaerd** [comment]
@Enderized omg thank you now i can use 10000mb instead of 2000
