### ISSUE TITLE
Applied Energistics ME Storage

### ISSUE THREAD

**Issue by Luminate091** [Iskallia/FunCraft#30]
In the 1.11 update, the AE2 mod's 1 and 4k ME Storage Component's recipe doesn't show up, and also doesn't work. Haven't tested with the another AE2 recipes.

**Comment by kalydrae** [comment]
I also cannot get the crafting recipe for 1k ME storage component.

**Comment by Enderized** [comment]
see #29

**Comment by swardhagen** [comment]
Same issue here, impossible to craft the 1k ME storage component.

**Comment by Enderized** [comment]
in 1.1.1 of the pack unable to craft due recipe issues- requiring stuff which is not yet avaible on public release (iTraders Magic Ore Dust) -

You could probably manually add the basic ones back in.

if you havent used Ender I/O up until now you could also downgrade the pack to 1.0 again? idk which other major additions were made in 1.1 due missing changelogs :D

Or wait for 1.2 which is said to be coming soon which will probably fix it aswell.

**Comment by Lurkking** [comment]
I had the same issue, it was the custom script on the latest version. Download the pack from twitch before the hot fix. Copy the contents of the scripts folder (pre hotfix) and move them into the scripts folder for the one you are playing on....worked for me.

**Comment by kalydrae** [comment]
@Lurkking I just tried this multiple times and it didn't work for me. Are you able to copy and paste your script folder content here pls?

**Comment by Lurkking** [comment]
@kalydrae No need to copy from the script folder really, just open the script folder of both your current download and the 1.0 (prehotfix) and move the contents over, pre hotfix to current, when it asks if you want to replace the contents say yes...it should swap the content. Or if you have notepad++ you can open the script and where it says recipes.remove (<appliedenergistics2 : wireless_terminal>) ; 
Down to 
Recipes.remove (<appliedenergistics2 : material : 18>) ; 
And delete that from the script it. Make sure you don't have the mod running or the launcher, when you modify the script. 
![15764178672122487586473402731634](https://user-images.githubusercontent.com/58718886/70863637-f342f700-1efe-11ea-854d-9bd7ac6d428a.jpg)

**Comment by Lurkking** [comment]
Maybe this will help....

 

    On Saturday, December 14, 2019, 09:09:32 PM PST, S Walker <notifications@github.com> wrote:  
 
 
@Lurkking I just tried this multiple times and it didn't work for me. Are you able to copy and paste your script folder content here pls?

**Comment by konsyr11** [comment]
Please try include that in the next update. Or actually... remove that :D

**Comment by kalydrae** [comment]
Thanks @Lurkking that is now working for me.
