### ISSUE TITLE
Pickaxe voiding mined items

### ISSUE THREAD

**Issue by Typical-Dragon** [Iskallia/FunCraft#33]
I was using my old pickaxe with a osoglass head fluxed electrum handle and an iron handle.
When I was Mining I was using my hammer to find ores. When I saw diamonds, I got my pickaxe and mined the diamonds but I didn't get any diamonds. When I got back to my house, I tested it on some stone. Poof I didn't get any(I had a full inventory when I mined the diamonds but not a full inventory when mining stone).  I made a new pickaxe and it is fine now. I think it is from the osoglass modifiers.

**Comment by ACG94** [comment]
Osgloglass has global traveler, so was your pickaxe linked to an inventory?

**Comment by Enderized** [comment]
Global Traveller from Osgloglas transfers items you mine directly into an linked inventory.
you can change the linked inventory by shift-clicking an inventory with your pickaxe.
you may disable global traveller aswell - i believe the hotkey for that was ' O '

**Comment by ACG94** [comment]
Hotkey is 'i"
'O' is to activate brown magic which teleports to a block anywhere which is bounded by looking at the desired block and pressing 'N'
