### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by StuartJ302** [Iskallia/FunCraft#35]
Game crashes on launch, saying:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

**Comment by StuartJ302** [comment]
Opening the game 1.12.2 did not fix

**Comment by StuartJ302** [comment]
This is with the public version, if that has any effect

**Comment by Enderized** [comment]
Using the 1.1.1 Version of the Pack? Can't reproduce this.
There should be a full crashlog somewhere at a subfolder at `\Twitch\Minecraft\Instances\FunCraft - FC\` i assume - maybe one could find more information out of that.

**Comment by StuartJ302** [comment]
[Crash report funcraft.txt](https://github.com/Iskallia/FunCraft/files/3990832/Crash.report.funcraft.txt)
Here is the crash report, will try to find the crashlog, if they are different

**Comment by StuartJ302** [comment]
[Crash report funcraft.txt](https://github.com/Iskallia/FunCraft/files/3990848/Crash.report.funcraft.txt)
Crashlog

**Comment by StuartJ302** [comment]
This does not happen with version 1.0.0

**Comment by StuartJ302** [comment]
I just checked, and I did recently (2019-12-12) update java, maybe that affected something?

**Comment by StuartJ302** [comment]
Deleting and redownloading minecraft did not change anything

**Comment by StuartJ302** [comment]
Fixed by installing a new version of the modpack
