### ISSUE TITLE
Creative mode voids excess items

### ISSUE THREAD

**Issue by swardhagen** [Iskallia/FunCraft#37]
If you have a full inventory and a magnet and go to creative, any items that you throw out or walk by will automatically be voided instead of being picked up by the magnet. This happened with a tinkers sword of mine and I had to revert to a backup to retrieve it, thus losing about an hour's worth of progress.

**Comment by Enderized** [comment]
Magnets pull everything near you towards you to pick up.
Creative indeed voids Items you pick up which is an intended behavior.

Can't find the "issue" with the pack itself here.

**Comment by swardhagen** [comment]
I see, I had never experienced this before so I assumed it was pack specific. In that case it's more of a suggestion than an issue I guess. Thanks for answering.
