### ISSUE TITLE
"Launching the game failed!" error message

### ISSUE THREAD

**Issue by TwiztedRipper** [Iskallia/FunCraft#40]
I receive this error message when I try to launch FunCraft - FC from the Minecraft launcher. I'm a complete noob when it comes to modded Minecraft and have never really been interested in it until I saw Iskall85's videos. I have no programming experience but I did save the message I was given as I'm sure it will help. I copied and pasted it below. I would LOVE to be able to play this and any help is greatly appreciated. I reinstalled Minecraft Java Edition just for this.

Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\torin\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

**Comment by Enderized** [comment]
Start a vanilla 1.12 game of Minecraft before starting FunCraft.

**Comment by TwiztedRipper** [comment]
Yup I'm such a noob. ROFLMFAO I knew it would be something simple like this. Thank You, Thank You, Thank You so much Enderized. This worked and I can now play FunCraft. (HAPPY SNOOPY DANCE) Now am I suppose to close the issue or can you?? Thanks again and much love.

**Comment by Enderized** [comment]
You would have to - i believe there was a button for that next to the comment button- I aint a moderator or sth for this or anything regarding iskallia- just like to help out =)
