### ISSUE TITLE
Glass bottles gets voided

### ISSUE THREAD

**Issue by swardhagen** [Iskallia/FunCraft#41]
Holding an empty glass bottle while right clicking a brewing stand voids the empty bottle. I discovered this on a ship in an end city.

**Comment by Enderized** [comment]
Can't replicate a "voiding" of Glass Bottles...

But what happens is, that when you rightclick on a block in the end with an Glass Bottle you get a Botania `Ender Air Bottle` which is required for some Botania crafting =)

**Comment by swardhagen** [comment]
Oh, so that's what happened! I already had some in my inventory so probably wouldn't notice a few more. That's that solved then, thanks!
