### ISSUE TITLE
Incuction Cells/Matrix for Mekanism

### ISSUE THREAD

**Issue by boog93** [Iskallia/FunCraft#44]
is:issue is:open The advanced, elite and ultimate induction cubes all have a capacity of 2.14Grf and dont stack in an Matrix. Any way to fix this

**Comment by Enderized** [comment]
2.14G is exactly the MAX_INT value (2,147,483,647) in which RF can be shown. https://i.imgur.com/dSdv4rR.png has 2.14GRF, yet still charges up https://i.imgur.com/lPC2lC7.png

They do stack tho even beyond that point.
You can check that yourself when you click on the little Energy Button to change the Energy Type to like IC2's EU: https://i.imgur.com/ZJcjrhZ.png , https://i.imgur.com/J74sfD8.png

**Comment by boog93** [comment]
Ah ok thx for checking that!Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Enderized <notifications@github.com> Date: 12/28/19  8:37 AM  (GMT-07:00) To: Iskallia/FunCraft <FunCraft@noreply.github.com> Cc: boog93 <djhope86@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Iskallia/FunCraft] Incuction Cells/Matrix for Mekanism (#44) 2.14G is exactly the MAX_INT value (2,147,483,647) in which RF can be shown. https://i.imgur.com/dSdv4rR.png has 2.14GRF, yet still charges up https://i.imgur.com/lPC2lC7.png
They do stack tho even beyond that point.
You can check that yourself when you click on the little Energy Button to change the Energy Type to like IC2's EU: https://i.imgur.com/ZJcjrhZ.png , https://i.imgur.com/J74sfD8.png

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Iskallia/FunCraft/issues/44?email_source=notifications\u0026email_token=AOEQ7AK4JD2TG2PUKUAP7KDQ25XEZA5CNFSM4KAN7Z52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYMFLA#issuecomment-569426604",
"url": "https://github.com/Iskallia/FunCraft/issues/44?email_source=notifications\u0026email_token=AOEQ7AK4JD2TG2PUKUAP7KDQ25XEZA5CNFSM4KAN7Z52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYMFLA#issuecomment-569426604",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
