### ISSUE TITLE
Unable to get Charged Quartz

### ISSUE THREAD

**Issue by PBandJellyToast** [Iskallia/FunCraft#55]
This is not really an issue, more of like a lack of knowledge. I am unable to get Charger Quartz for AE2 system, I know about specific "Chargers" for them, but to make one I need to obtain at least 2 Charged Quartz. I have tried just grinding for them, no luck( only got 4 stacks of "common" ones.

**Comment by Enderized** [comment]
Charged Certus Quartz Ore are also a thing. These generate at a lower rate than the normal certus quartz.
But they do 100% generate

**Comment by PBandJellyToast** [comment]
Thank you for the response. I knew about the ore but it looks like I just haven't found any...
