### ISSUE TITLE
No broken spawner recipe

### ISSUE THREAD

**Issue by PBandJellyToast** [Iskallia/FunCraft#56]
That's pretty much it, cant get Powered Spawner because of that

**Comment by Enderized** [comment]
Which Version of FunCraft are you currently using?
1.1 or 1.2 (yet to be public released) ?

In 1.2 you should have a recipe for Zombie Broken Spawner
In 1.1, recipe might be broken due missing items.

Else, same as #49

**Comment by PBandJellyToast** [comment]
I'm on 1.1, sorry for duplicate issues. Oh btw, when will you release the 1.2 version? (asking for a friend)

**Comment by Enderized** [comment]
Oh i would have released it weeks ago to fix all the issues about missing recipes, tho I'm no developer and just helping out aswering questions here on my own accord-

I could get a temp script file setup for you to install to get a recipe of equal value to have access to the broken spawner if you like later this day.

**Comment by PBandJellyToast** [comment]
There is no need for that, but thank you for an offer)
