### ISSUE TITLE
Constant Freezing

### ISSUE THREAD

**Issue by Koris95** [Iskallia/FunCraft#58]
The game occasionally freezes continuously for 3-7 seconds every 4 seconds.
I've tried installing OptiFine in case it was a performance issue, but it didn't help.

Thanks

**Comment by Enderized** [comment]
Have you allocated enough RAM via the Twitch Client?

**Comment by Koris95** [comment]
I can't say I have, how do I do that?

**Comment by Enderized** [comment]
You can either allocate RAM pack specific, by clicking on the pack in Twitch -> Mods -> Minecraft -> Pack -> Packoptions -> Uncheck then 2nd Checkbox, then you should have a slider allowing you to chose the RAM you want.

Alternatively you can set RAM directly in Twitch so you dont have to allocate on each new profile.

For that you click the 3 horizontal bars on the top left corner in twitch ->File -> Settings  -> Minecraft -> Java Settings and use the slider there

**Comment by Koris95** [comment]
Yup, that solved it thanks :)
I'm new to modded :P
