### ISSUE TITLE
wings of the bat

### ISSUE THREAD

**Issue by TheDutchMC04** [Iskallia/FunCraft#8]
dont know if intentional, since all other ways of creative flight are disabled, but wings of the bat from AA (I think) isnt

**Comment by Enderized** [comment]
Yes indeed from AA - tho as far as I remember should be disabled (bats drop disabled) tho still obtainable through Chest Loot.

**Comment by jmilthedude** [comment]
Yes, and AA dungeon loot is either on or off. 

Recipe will be changed with the addition of EnderIO. :)
